# Generated by Django 3.2.14 on 2022-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220728_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Paid')], default='P', max_length=1),
        ),
    ]
